title: AIRExcelencia
description: Seguros personales con enfoque fiscal claro. Vida, GMM, Auto, Educación y Retiro.
url: https://airexcelencia.github.io
baseurl: "/airexcelencia"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
language: es-MX